// USA States and Cities data for checkout form
export interface State {
  code: string;
  name: string;
  cities: string[];
}

export const USA_STATES: State[] = [
  {
    code: "AL",
    name: "Alabama",
    cities: [
      "Birmingham",
      "Montgomery",
      "Mobile",
      "Huntsville",
      "Tuscaloosa",
      "Hoover",
      "Dothan",
      "Auburn",
      "Decatur",
      "Madison",
    ],
  },
  {
    code: "AK",
    name: "Alaska",
    cities: [
      "Anchorage",
      "Fairbanks",
      "Juneau",
      "Sitka",
      "Wasilla",
      "Kenai",
      "Ketchikan",
      "Kodiak",
      "Bethel",
      "Palmer",
    ],
  },
  {
    code: "AZ",
    name: "Arizona",
    cities: [
      "Phoenix",
      "Tucson",
      "Mesa",
      "Chandler",
      "Scottsdale",
      "Glendale",
      "Gilbert",
      "Tempe",
      "Peoria",
      "Surprise",
    ],
  },
  {
    code: "AR",
    name: "Arkansas",
    cities: [
      "Little Rock",
      "Fort Smith",
      "Fayetteville",
      "Springdale",
      "Jonesboro",
      "North Little Rock",
      "Conway",
      "Rogers",
      "Pine Bluff",
      "Bentonville",
    ],
  },
  {
    code: "CA",
    name: "California",
    cities: [
      "Los Angeles",
      "San Diego",
      "San Jose",
      "San Francisco",
      "Fresno",
      "Sacramento",
      "Long Beach",
      "Oakland",
      "Bakersfield",
      "Anaheim",
      "Santa Ana",
      "Riverside",
      "Stockton",
      "Irvine",
      "Chula Vista",
      "Fremont",
      "San Bernardino",
      "Modesto",
      "Fontana",
      "Oxnard",
    ],
  },
  {
    code: "CO",
    name: "Colorado",
    cities: [
      "Denver",
      "Colorado Springs",
      "Aurora",
      "Fort Collins",
      "Lakewood",
      "Thornton",
      "Westminster",
      "Pueblo",
      "Centennial",
      "Boulder",
    ],
  },
  {
    code: "CT",
    name: "Connecticut",
    cities: [
      "Bridgeport",
      "New Haven",
      "Hartford",
      "Stamford",
      "Waterbury",
      "Norwalk",
      "Danbury",
      "New Britain",
      "West Hartford",
      "Greenwich",
    ],
  },
  {
    code: "DE",
    name: "Delaware",
    cities: [
      "Wilmington",
      "Dover",
      "Newark",
      "Middletown",
      "Smyrna",
      "Milford",
      "Seaford",
      "Georgetown",
      "Elsmere",
      "New Castle",
    ],
  },
  {
    code: "FL",
    name: "Florida",
    cities: [
      "Jacksonville",
      "Miami",
      "Tampa",
      "Orlando",
      "St. Petersburg",
      "Hialeah",
      "Tallahassee",
      "Fort Lauderdale",
      "Port St. Lucie",
      "Cape Coral",
      "Pembroke Pines",
      "Hollywood",
      "Miramar",
      "Gainesville",
      "Coral Springs",
      "Miami Gardens",
      "Clearwater",
      "Palm Bay",
      "West Palm Beach",
      "Pompano Beach",
    ],
  },
  {
    code: "GA",
    name: "Georgia",
    cities: [
      "Atlanta",
      "Augusta",
      "Columbus",
      "Savannah",
      "Athens",
      "Sandy Springs",
      "Roswell",
      "Macon",
      "Albany",
      "Johns Creek",
    ],
  },
  {
    code: "HI",
    name: "Hawaii",
    cities: [
      "Honolulu",
      "Pearl City",
      "Hilo",
      "Kailua",
      "Kaneohe",
      "Waipahu",
      "Kahului",
      "Kihei",
      "Kailua-Kona",
      "Kaneohe",
    ],
  },
  {
    code: "ID",
    name: "Idaho",
    cities: [
      "Boise",
      "Nampa",
      "Meridian",
      "Idaho Falls",
      "Pocatello",
      "Caldwell",
      "Coeur d'Alene",
      "Twin Falls",
      "Lewiston",
      "Post Falls",
    ],
  },
  {
    code: "IL",
    name: "Illinois",
    cities: [
      "Chicago",
      "Aurora",
      "Rockford",
      "Joliet",
      "Naperville",
      "Springfield",
      "Peoria",
      "Elgin",
      "Waukegan",
      "Cicero",
    ],
  },
  {
    code: "IN",
    name: "Indiana",
    cities: [
      "Indianapolis",
      "Fort Wayne",
      "Evansville",
      "South Bend",
      "Hammond",
      "Bloomington",
      "Gary",
      "Carmel",
      "Fishers",
      "Muncie",
    ],
  },
  {
    code: "IA",
    name: "Iowa",
    cities: [
      "Des Moines",
      "Cedar Rapids",
      "Davenport",
      "Sioux City",
      "Iowa City",
      "Waterloo",
      "Council Bluffs",
      "Ames",
      "West Des Moines",
      "Dubuque",
    ],
  },
  {
    code: "KS",
    name: "Kansas",
    cities: [
      "Wichita",
      "Overland Park",
      "Kansas City",
      "Topeka",
      "Olathe",
      "Lawrence",
      "Shawnee",
      "Manhattan",
      "Lenexa",
      "Salina",
    ],
  },
  {
    code: "KY",
    name: "Kentucky",
    cities: [
      "Louisville",
      "Lexington",
      "Bowling Green",
      "Owensboro",
      "Covington",
      "Hopkinsville",
      "Richmond",
      "Florence",
      "Georgetown",
      "Henderson",
    ],
  },
  {
    code: "LA",
    name: "Louisiana",
    cities: [
      "New Orleans",
      "Baton Rouge",
      "Shreveport",
      "Lafayette",
      "Lake Charles",
      "Kenner",
      "Bossier City",
      "Monroe",
      "Alexandria",
      "Houma",
    ],
  },
  {
    code: "ME",
    name: "Maine",
    cities: [
      "Portland",
      "Lewiston",
      "Bangor",
      "South Portland",
      "Auburn",
      "Biddeford",
      "Sanford",
      "Saco",
      "Augusta",
      "Westbrook",
    ],
  },
  {
    code: "MD",
    name: "Maryland",
    cities: [
      "Baltimore",
      "Frederick",
      "Rockville",
      "Gaithersburg",
      "Bowie",
      "Hagerstown",
      "Annapolis",
      "College Park",
      "Salisbury",
      "Laurel",
    ],
  },
  {
    code: "MA",
    name: "Massachusetts",
    cities: [
      "Boston",
      "Worcester",
      "Springfield",
      "Cambridge",
      "Lowell",
      "Brockton",
      "New Bedford",
      "Quincy",
      "Lynn",
      "Newton",
    ],
  },
  {
    code: "MI",
    name: "Michigan",
    cities: [
      "Detroit",
      "Grand Rapids",
      "Warren",
      "Sterling Heights",
      "Lansing",
      "Ann Arbor",
      "Flint",
      "Dearborn",
      "Livonia",
      "Westland",
    ],
  },
  {
    code: "MN",
    name: "Minnesota",
    cities: [
      "Minneapolis",
      "Saint Paul",
      "Rochester",
      "Duluth",
      "Bloomington",
      "Brooklyn Park",
      "Plymouth",
      "Saint Cloud",
      "Eagan",
      "Woodbury",
    ],
  },
  {
    code: "MS",
    name: "Mississippi",
    cities: [
      "Jackson",
      "Gulfport",
      "Southaven",
      "Hattiesburg",
      "Biloxi",
      "Meridian",
      "Tupelo",
      "Greenville",
      "Olive Branch",
      "Horn Lake",
    ],
  },
  {
    code: "MO",
    name: "Missouri",
    cities: [
      "Kansas City",
      "Saint Louis",
      "Springfield",
      "Independence",
      "Columbia",
      "Lee's Summit",
      "O'Fallon",
      "Saint Joseph",
      "Saint Charles",
      "Saint Peters",
    ],
  },
  {
    code: "MT",
    name: "Montana",
    cities: [
      "Billings",
      "Missoula",
      "Great Falls",
      "Bozeman",
      "Butte",
      "Helena",
      "Kalispell",
      "Havre",
      "Anaconda",
      "Miles City",
    ],
  },
  {
    code: "NE",
    name: "Nebraska",
    cities: [
      "Omaha",
      "Lincoln",
      "Bellevue",
      "Grand Island",
      "Kearney",
      "Fremont",
      "Hastings",
      "North Platte",
      "Norfolk",
      "Columbus",
    ],
  },
  {
    code: "NV",
    name: "Nevada",
    cities: [
      "Las Vegas",
      "Henderson",
      "Reno",
      "North Las Vegas",
      "Sparks",
      "Carson City",
      "Fernley",
      "Elko",
      "Mesquite",
      "Boulder City",
    ],
  },
  {
    code: "NH",
    name: "New Hampshire",
    cities: [
      "Manchester",
      "Nashua",
      "Concord",
      "Derry",
      "Dover",
      "Rochester",
      "Salem",
      "Goffstown",
      "Hudson",
      "Londonderry",
    ],
  },
  {
    code: "NJ",
    name: "New Jersey",
    cities: [
      "Newark",
      "Jersey City",
      "Paterson",
      "Elizabeth",
      "Edison",
      "Woodbridge",
      "Lakewood",
      "Toms River",
      "Hamilton",
      "Trenton",
    ],
  },
  {
    code: "NM",
    name: "New Mexico",
    cities: [
      "Albuquerque",
      "Las Cruces",
      "Rio Rancho",
      "Santa Fe",
      "Roswell",
      "Farmington",
      "Clovis",
      "Hobbs",
      "Alamogordo",
      "Carlsbad",
    ],
  },
  {
    code: "NY",
    name: "New York",
    cities: [
      "New York City",
      "Buffalo",
      "Rochester",
      "Yonkers",
      "Syracuse",
      "Albany",
      "New Rochelle",
      "Mount Vernon",
      "Schenectady",
      "Utica",
    ],
  },
  {
    code: "NC",
    name: "North Carolina",
    cities: [
      "Charlotte",
      "Raleigh",
      "Greensboro",
      "Durham",
      "Winston-Salem",
      "Fayetteville",
      "Cary",
      "Wilmington",
      "High Point",
      "Concord",
    ],
  },
  {
    code: "ND",
    name: "North Dakota",
    cities: [
      "Fargo",
      "Bismarck",
      "Grand Forks",
      "Minot",
      "West Fargo",
      "Williston",
      "Dickinson",
      "Mandan",
      "Jamestown",
      "Wahpeton",
    ],
  },
  {
    code: "OH",
    name: "Ohio",
    cities: [
      "Columbus",
      "Cleveland",
      "Cincinnati",
      "Toledo",
      "Akron",
      "Dayton",
      "Parma",
      "Canton",
      "Youngstown",
      "Lorain",
    ],
  },
  {
    code: "OK",
    name: "Oklahoma",
    cities: [
      "Oklahoma City",
      "Tulsa",
      "Norman",
      "Broken Arrow",
      "Lawton",
      "Edmond",
      "Moore",
      "Midwest City",
      "Enid",
      "Stillwater",
    ],
  },
  {
    code: "OR",
    name: "Oregon",
    cities: [
      "Portland",
      "Salem",
      "Eugene",
      "Gresham",
      "Hillsboro",
      "Bend",
      "Beaverton",
      "Medford",
      "Springfield",
      "Corvallis",
    ],
  },
  {
    code: "PA",
    name: "Pennsylvania",
    cities: [
      "Philadelphia",
      "Pittsburgh",
      "Allentown",
      "Erie",
      "Reading",
      "Scranton",
      "Bethlehem",
      "Lancaster",
      "Harrisburg",
      "Altoona",
    ],
  },
  {
    code: "RI",
    name: "Rhode Island",
    cities: [
      "Providence",
      "Warwick",
      "Cranston",
      "Pawtucket",
      "East Providence",
      "Woonsocket",
      "Newport",
      "Central Falls",
      "Westerly",
      "Cumberland",
    ],
  },
  {
    code: "SC",
    name: "South Carolina",
    cities: [
      "Columbia",
      "Charleston",
      "North Charleston",
      "Mount Pleasant",
      "Rock Hill",
      "Greenville",
      "Summerville",
      "Sumter",
      "Hilton Head Island",
      "Spartanburg",
    ],
  },
  {
    code: "SD",
    name: "South Dakota",
    cities: [
      "Sioux Falls",
      "Rapid City",
      "Aberdeen",
      "Brookings",
      "Watertown",
      "Mitchell",
      "Yankton",
      "Pierre",
      "Huron",
      "Vermillion",
    ],
  },
  {
    code: "TN",
    name: "Tennessee",
    cities: [
      "Nashville",
      "Memphis",
      "Knoxville",
      "Chattanooga",
      "Clarksville",
      "Murfreesboro",
      "Franklin",
      "Jackson",
      "Johnson City",
      "Bartlett",
    ],
  },
  {
    code: "TX",
    name: "Texas",
    cities: [
      "Houston",
      "San Antonio",
      "Dallas",
      "Austin",
      "Fort Worth",
      "El Paso",
      "Arlington",
      "Corpus Christi",
      "Plano",
      "Laredo",
      "Lubbock",
      "Garland",
      "Irving",
      "Amarillo",
      "Grand Prairie",
      "Brownsville",
      "Pasadena",
      "Mesquite",
      "McKinney",
      "Killeen",
    ],
  },
  {
    code: "UT",
    name: "Utah",
    cities: [
      "Salt Lake City",
      "West Valley City",
      "Provo",
      "West Jordan",
      "Orem",
      "Sandy",
      "Ogden",
      "St. George",
      "Layton",
      "Taylorsville",
    ],
  },
  {
    code: "VT",
    name: "Vermont",
    cities: [
      "Burlington",
      "Essex",
      "South Burlington",
      "Colchester",
      "Rutland",
      "Montpelier",
      "Barre",
      "St. Albans",
      "Brattleboro",
      "Milton",
    ],
  },
  {
    code: "VA",
    name: "Virginia",
    cities: [
      "Virginia Beach",
      "Norfolk",
      "Chesapeake",
      "Richmond",
      "Newport News",
      "Alexandria",
      "Hampton",
      "Portsmouth",
      "Suffolk",
      "Roanoke",
    ],
  },
  {
    code: "WA",
    name: "Washington",
    cities: [
      "Seattle",
      "Spokane",
      "Tacoma",
      "Vancouver",
      "Bellevue",
      "Kent",
      "Everett",
      "Renton",
      "Yakima",
      "Federal Way",
    ],
  },
  {
    code: "WV",
    name: "West Virginia",
    cities: [
      "Charleston",
      "Huntington",
      "Parkersburg",
      "Morgantown",
      "Wheeling",
      "Martinsburg",
      "Fairmont",
      "Beckley",
      "Clarksburg",
      "South Charleston",
    ],
  },
  {
    code: "WI",
    name: "Wisconsin",
    cities: [
      "Milwaukee",
      "Madison",
      "Green Bay",
      "Kenosha",
      "Racine",
      "Appleton",
      "Waukesha",
      "Oshkosh",
      "Eau Claire",
      "Janesville",
    ],
  },
  {
    code: "WY",
    name: "Wyoming",
    cities: [
      "Cheyenne",
      "Casper",
      "Laramie",
      "Gillette",
      "Rock Springs",
      "Sheridan",
      "Green River",
      "Evanston",
      "Riverton",
      "Jackson",
    ],
  },
];

export const getCitiesByState = (stateCode: string): string[] => {
  const state = USA_STATES.find((s) => s.code === stateCode);
  return state ? state.cities : [];
};

export const getStateByCode = (stateCode: string): State | undefined => {
  return USA_STATES.find((s) => s.code === stateCode);
};
